import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { AppHeader } from "@/components/app-header";
import { ProgressButton } from "@/components/progress-button";
import { canAccess } from "@/lib/access";
import { requireUser } from "@/lib/auth";
import { query } from "@/lib/db";

type LessonRow={id:string;title:string;description:string;video_provider:string|null;video_id:string|null;duration_seconds:number|null;position:number;is_preview:boolean;course_id:string;course_slug:string;course_title:string;included_in_all_access:boolean;completed_at:Date|null};
export const dynamic="force-dynamic";
export default async function LessonPage({params}:{params:Promise<{id:string}>}){const user=await requireUser();const{id}=await params;const result=await query<LessonRow>(`SELECT l.*,c.slug course_slug,c.title course_title,c.included_in_all_access,lp.completed_at FROM lessons l JOIN courses c ON c.id=l.course_id LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.user_id=$2 WHERE l.id=$1 AND l.status='PUBLISHED' AND c.status='PUBLISHED'`,[id,user.id]);const lesson=result.rows[0];if(!lesson)notFound();const allowed=lesson.is_preview||await canAccess(user.id,{type:"COURSE",id:lesson.course_id,includedInAllAccess:lesson.included_in_all_access});if(!allowed)redirect(`/curso/${lesson.course_slug}`);const siblings=(await query<{id:string;title:string;position:number}>("SELECT id,title,position FROM lessons WHERE course_id=$1 AND status='PUBLISHED' ORDER BY position",[lesson.course_id])).rows;const index=siblings.findIndex(item=>item.id===lesson.id);const driveVideo=lesson.video_provider==='drive'&&lesson.video_id?`https://drive.google.com/file/d/${lesson.video_id}/preview`:null;return <main className="lesson-page"><AppHeader user={user}/><div className="lesson-layout"><section><div className="video-shell">{driveVideo?<iframe src={driveVideo} title={lesson.title} allow="autoplay; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>:<div><span>PLAYER SEGURO</span><strong>O vídeo será entregue pelo provedor privado configurado.</strong><small>{lesson.video_provider&&lesson.video_id?`${lesson.video_provider} · conteúdo protegido`:"Provedor de vídeo pendente"}</small></div>}</div><p className="eyebrow red-text">{lesson.course_title} · AULA {String(lesson.position).padStart(2,"0")}</p><h1>{lesson.title}</h1><p>{lesson.description}</p><div className="lesson-actions"><ProgressButton lessonId={lesson.id} completed={Boolean(lesson.completed_at)}/><div>{index>0&&<Link className="button outline" href={`/aula/${siblings[index-1].id}`}>← ANTERIOR</Link>}{index<siblings.length-1&&<Link className="button outline" href={`/aula/${siblings[index+1].id}`}>PRÓXIMA →</Link>}</div></div></section><aside><div><p className="eyebrow">CONTEÚDO DO CURSO</p><h2>{lesson.course_title}</h2></div>{siblings.map(item=><Link key={item.id} className={item.id===lesson.id?"active":""} href={`/aula/${item.id}`}><span>{String(item.position).padStart(2,"0")}</span>{item.title}</Link>)}</aside></div></main>}
