const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const login=$('#loginScreen'),app=$('#app');
$('#enterBtn').addEventListener('click',loginUser);
$('#password').addEventListener('keydown',e=>{if(e.key==='Enter')loginUser()});
function loginUser(){const valid=$('#email').value.trim().toLowerCase()==='operador@forja.com'&&$('#password').value==='forja2026';if(!valid){$('#loginError').textContent='CREDENCIAIS NÃO RECONHECIDAS. TENTE NOVAMENTE.';return}$('#loginError').textContent='';login.classList.add('hidden');app.classList.remove('hidden');window.scrollTo(0,0)}
$('#logoutBtn').addEventListener('click',()=>{app.classList.add('hidden');login.classList.remove('hidden');window.scrollTo(0,0)});
const slides=[
 {kicker:'TRILHA 03 · NEUROCIÊNCIA APLICADA',title:'O CÓDIGO<br><em>DA PRESENÇA</em>',description:'Domine seu estado interno, amplifique sua presença e transforme intenção em ação precisa.',module:'presenca'},
 {kicker:'TRILHA 04 · ALTA PERFORMANCE',title:'RESILIÊNCIA<br><em>DE ELITE</em>',description:'Construa estabilidade emocional para decidir com clareza quando a pressão aumenta.',module:'resiliencia'},
 {kicker:'TREINO GUIADO · FOCO PROFUNDO',title:'COMANDO<br><em>INTERNO</em>',description:'Um protocolo prático para regular o corpo, silenciar o ruído e recuperar o controle.',module:'disciplina'}];
let currentSlide=0,slideTimer;
function renderSlide(index){currentSlide=(index+slides.length)%slides.length;$$('.hero-image').forEach((el,i)=>el.classList.toggle('active',i===currentSlide));$$('#slideDots i').forEach((el,i)=>el.classList.toggle('active',i===currentSlide));$('#heroKicker').textContent=slides[currentSlide].kicker;$('#heroTitle').innerHTML=slides[currentSlide].title;$('#heroDescription').textContent=slides[currentSlide].description;$('#slideCount').textContent=`0${currentSlide+1} / 03`;const bar=$('#heroProgress');bar.style.animation='none';void bar.offsetWidth;bar.style.animation='timer 7s linear infinite';clearInterval(slideTimer);slideTimer=setInterval(()=>renderSlide(currentSlide+1),7000)}
$('#prevSlide').addEventListener('click',()=>renderSlide(currentSlide-1));$('#nextSlide').addEventListener('click',()=>renderSlide(currentSlide+1));$$('#slideDots i').forEach((dot,i)=>dot.addEventListener('click',()=>renderSlide(i)));renderSlide(0);
const modules={
 fundamentos:{title:'Fundamentos da Forja',kicker:'MÓDULO 01 · FUNDAMENTOS',description:'A base invisível de toda mudança duradoura.',image:'assets/banners/foco.png',lessons:['O mapa da transformação','Identidade e ambiente','O ciclo do hábito','Atenção como recurso','A regra dos 2 minutos','Ritmo e consistência','O protocolo matinal','Missão da semana']},
 disciplina:{title:'Disciplina sem Esforço',kicker:'MÓDULO 02 · PROTOCOLOS',description:'Desenhe um sistema que trabalha por você, mesmo nos dias difíceis.',image:'assets/banners/foco.png',lessons:['O ritual de entrada','Fricção e ambiente','Motivação não é estratégia','O contrato consigo mesmo','Recuperação inteligente','Plano de execução']},
 presenca:{title:'O Código da Presença',kicker:'MÓDULO 03 · NEUROCIÊNCIA APLICADA',description:'Estado interno, comunicação e influência sob controle.',image:'assets/banners/presenca.png',lessons:['O corpo que comunica','Estado interno','Voz e autoridade','Atenção no ambiente','Influência sem esforço','Presença sob pressão','Operação final']},
 resiliencia:{title:'Resiliência de Elite',kicker:'MÓDULO 04 · ALTA PERFORMANCE',description:'O protocolo mental para operar com precisão sob pressão.',image:'assets/banners/resiliencia.png',lessons:['A fisiologia do estresse','Responder em vez de reagir','Treino de desconforto','Recuperação do operador','Cenários de pressão','Protocolo de crise','Liderança estável','O pós-ação','Teste de campo']},
 decisao:{title:'Arquitetura da Decisão',kicker:'MÓDULO 05 · ESTRATÉGIA MENTAL',description:'Decida com velocidade, clareza e responsabilidade em cenários complexos.',image:'assets/banners/foco.png',lessons:['O cérebro sob incerteza','A anatomia de uma decisão','Viés, medo e paralisia','Prioridade versus urgência','O método dos três cenários','Decisão sob pressão','Como corrigir a rota','Protocolo de decisão final']},
 lideranca:{title:'Liderança Antifrágil',kicker:'MÓDULO 06 · COMANDO E LIDERANÇA',description:'Lidere pessoas com presença, confiança e direção mesmo quando o cenário muda.',image:'assets/banners/resiliencia.png',lessons:['Liderar começa por si','Autoridade versus autoritarismo','Comunicação de comando','Segurança psicológica na equipe','Feedback claro e direto','Delegação sem perda de controle','Decisões difíceis e conversas corajosas','Como agir durante uma crise','Cultura, exemplo e confiança','A missão do líder antifrágil']}};
function openModule(key){const m=modules[key];if(!m)return;$('#modalVisual').style.backgroundImage=`url('${m.image}')`;$('#modalKicker').textContent=m.kicker;$('#modalTitle').textContent=m.title;$('#modalDescription').textContent=m.description;$('#lessonList').innerHTML=m.lessons.map((lesson,i)=>`<div class="lesson-item"><span>${String(i+1).padStart(2,'0')}</span><strong>Aula ${String(i+1).padStart(2,'0')} · ${lesson}</strong><small>${i===0?'▶ ASSISTIR':'○ DISPONÍVEL'}</small></div>`).join('');$('#lessonModal').classList.remove('hidden');document.body.style.overflow='hidden'}
$$('.media-card:not(.locked-card)').forEach(card=>card.addEventListener('click',()=>openModule(card.dataset.module)));$('#watchHero').addEventListener('click',()=>openModule(slides[currentSlide].module));
function closeModal(){$('#lessonModal').classList.add('hidden');document.body.style.overflow=''}
$('#closeModal').addEventListener('click',closeModal);$('#lessonModal').addEventListener('click',e=>{if(e.target.id==='lessonModal')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$$('.filters button').forEach(button=>button.addEventListener('click',()=>{$$('.filters button').forEach(b=>b.classList.remove('active'));button.classList.add('active')}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('revealed');revealObserver.unobserve(entry.target)}}),{threshold:.14});
$$('.content-row,.mission-banner,.module-card').forEach(element=>{element.classList.add('reveal');revealObserver.observe(element)});
