import Link from "next/link";
import { notFound } from "next/navigation";
import { AppHeader } from "@/components/app-header";
import { CheckoutButton } from "@/components/checkout-button";
import { canAccess } from "@/lib/access";
import { requireUser } from "@/lib/auth";
import { query } from "@/lib/db";

type Course={id:string;slug:string;title:string;subtitle:string;description:string;thumbnail:string|null;instructor:string;category:string;level:string;included_in_all_access:boolean;monthly_price_cents:number|null;offer_slug:string|null};
type Lesson={id:string;title:string;description:string;duration_seconds:number|null;position:number;is_preview:boolean};
export const dynamic="force-dynamic";
export default async function CoursePage({params}:{params:Promise<{slug:string}>}){const user=await requireUser();const{slug}=await params;const result=await query<Course>(`SELECT c.*,o.slug AS offer_slug FROM courses c LEFT JOIN offers o ON o.resource_type='COURSE' AND o.resource_id=c.id AND o.active=true WHERE c.slug=$1 AND c.status='PUBLISHED' LIMIT 1`,[slug]);const course=result.rows[0];if(!course)notFound();const allowed=await canAccess(user.id,{type:"COURSE",id:course.id,includedInAllAccess:course.included_in_all_access});const lessons=(await query<Lesson>("SELECT id,title,description,duration_seconds,position,is_preview FROM lessons WHERE course_id=$1 AND status='PUBLISHED' ORDER BY position",[course.id])).rows;const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"/liderflix";const image=course.thumbnail||`${basePath}/assets/banners/presenca.png`;return <main className="platform"><AppHeader user={user}/><section className="course-hero" style={{backgroundImage:`linear-gradient(90deg,#050505 0%,#050505e8 45%,transparent 90%),linear-gradient(0deg,#050505,transparent 40%),url('${image}')`}}><div><p className="eyebrow red-text">{course.category}</p><h1>{course.title}</h1><h2>{course.subtitle}</h2><p>{course.description}</p><div className="course-facts"><span>INSTRUTOR · {course.instructor}</span><span>{lessons.length} AULAS</span><span>{course.level}</span></div>{allowed?<Link className="button red" href={lessons[0]?`/aula/${lessons[0].id}`:"#aulas"}>▶ COMEÇAR AGORA</Link>:<div className="purchase-box"><strong>{course.monthly_price_cents?`${(course.monthly_price_cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}/mês`:"Consulte a disponibilidade"}</strong>{course.offer_slug&&<CheckoutButton offerId={course.offer_slug} label="ASSINAR ESTE CURSO"/>}<span>Também disponível no LiderFlix Completo</span></div>}</div></section><section className="lesson-catalog" id="aulas"><div><p className="eyebrow">CONTEÚDO DA FORMAÇÃO</p><h2>{lessons.length} AULAS PARA TRANSFORMAR SUA LIDERANÇA</h2></div><div>{lessons.map(lesson=><article key={lesson.id}><span>{String(lesson.position).padStart(2,"0")}</span><div><h3>{lesson.title}</h3><p>{lesson.description}</p></div><small>{lesson.duration_seconds?`${Math.round(lesson.duration_seconds/60)} MIN`:"AULA"}</small>{allowed||lesson.is_preview?<Link href={`/aula/${lesson.id}`}>▶</Link>:<b>🔒</b>}</article>)}</div></section></main>}
