import { createHash } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import type Stripe from "stripe";
import { transaction } from "@/lib/db";
import { getStripe } from "@/lib/stripe";

export async function POST(request:NextRequest){const signature=request.headers.get("stripe-signature");const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!signature||!secret)return NextResponse.json({error:"Webhook não configurado"},{status:503});const payload=await request.text();let event:Stripe.Event;try{event=getStripe().webhooks.constructEvent(payload,signature,secret)}catch{return NextResponse.json({error:"Assinatura inválida"},{status:400})}try{await transaction(async client=>{const inserted=await client.query("INSERT INTO processed_webhook_events(stripe_event_id,event_type,payload_sha256) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING stripe_event_id",[event.id,event.type,createHash("sha256").update(payload).digest("hex")]);if(!inserted.rowCount)return;
    if(event.type==="checkout.session.completed"||event.type==="checkout.session.async_payment_succeeded"){const session=event.data.object as Stripe.Checkout.Session;await client.query("UPDATE purchases SET status='PAID',stripe_payment_intent_id=COALESCE($2,stripe_payment_intent_id),amount_cents=$3,currency=COALESCE($4,currency),customer_email=COALESCE($5,customer_email),updated_at=now() WHERE stripe_checkout_session_id=$1",[session.id,typeof session.payment_intent==="string"?session.payment_intent:null,session.amount_total,session.currency,session.customer_details?.email]);const offerId=session.metadata?.offerId;const userId=session.metadata?.userId||session.client_reference_id;if(!offerId)return;const offer=(await client.query<{resource_type:string|null;resource_id:string|null}>("SELECT resource_type,resource_id FROM offers WHERE id=$1",[offerId])).rows[0];const purchase=(await client.query<{id:string}>("SELECT id FROM purchases WHERE stripe_checkout_session_id=$1",[session.id])).rows[0];const campaign=(await client.query<{id:string;selectable_course_count:number;duration_unit:string;duration_value:number|null;custom_expires_at:Date|null}>("SELECT id,selectable_course_count,duration_unit,duration_value,custom_expires_at FROM campaigns WHERE stripe_price_id=(SELECT stripe_price_id FROM offers WHERE id=$1) AND status='ACTIVE'",[offerId])).rows[0];if(campaign&&purchase){await client.query("INSERT INTO campaign_benefits(campaign_id,purchase_id,user_id,recipient_email,selectable_course_count,status) VALUES($1,$2,$3,$4,$5,'PENDING') ON CONFLICT(campaign_id,purchase_id) DO NOTHING",[campaign.id,purchase.id,userId||null,session.customer_details?.email||session.customer_email,campaign.selectable_course_count])}else if(userId&&offer?.resource_type&&session.mode==="payment"){await client.query("INSERT INTO access_grants(user_id,resource_type,resource_id,source,source_reference,status) VALUES($1,$2,$3,'PURCHASE',$4,'ACTIVE') ON CONFLICT DO NOTHING",[userId,offer.resource_type,offer.resource_id,session.id])}}
    if(event.type.startsWith("customer.subscription.")){const subscription=event.data.object as Stripe.Subscription;const userId=subscription.metadata.userId;const offerId=subscription.metadata.offerId;if(!userId||!offerId)return;const offer=(await client.query<{resource_type:string;resource_id:string|null;stripe_price_id:string}>("SELECT resource_type,resource_id,stripe_price_id FROM offers WHERE id=$1",[offerId])).rows[0];if(!offer)return;const item=subscription.items.data[0];const periodEnd=item?.current_period_end?new Date(item.current_period_end*1000):null;const active=["active","trialing"].includes(subscription.status);await client.query(`INSERT INTO subscriptions(user_id,resource_type,resource_id,stripe_customer_id,stripe_subscription_id,stripe_price_id,status,current_period_end,cancel_at_period_end) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(stripe_subscription_id) DO UPDATE SET status=$7,current_period_end=$8,cancel_at_period_end=$9,updated_at=now()`,[userId,offer.resource_type,offer.resource_id,String(subscription.customer),subscription.id,item?.price.id??offer.stripe_price_id,mapSubscriptionStatus(subscription.status),periodEnd,subscription.cancel_at_period_end]);if(active){await client.query(`INSERT INTO access_grants(user_id,resource_type,resource_id,source,source_reference,starts_at,expires_at,status) VALUES($1,$2,$3,'SUBSCRIPTION',$4,now(),$5,'ACTIVE') ON CONFLICT DO NOTHING`,[userId,offer.resource_type,offer.resource_id,subscription.id,periodEnd]);await client.query("UPDATE access_grants SET expires_at=$2,status='ACTIVE',updated_at=now() WHERE source='SUBSCRIPTION' AND source_reference=$1",[subscription.id,periodEnd])}else{await client.query("UPDATE access_grants SET expires_at=COALESCE($2,expires_at),updated_at=now() WHERE source='SUBSCRIPTION' AND source_reference=$1",[subscription.id,periodEnd])}}
  });return NextResponse.json({received:true})}catch(error){console.error("Stripe webhook failure",event.id,error);return NextResponse.json({error:"Falha ao processar evento"},{status:500})}}
function mapSubscriptionStatus(status:Stripe.Subscription.Status){if(status==="active"||status==="trialing")return"ACTIVE";if(status==="past_due"||status==="unpaid")return"PAST_DUE";if(status==="canceled")return"CANCELLED";return"INCOMPLETE"}
